<a href="https://colab.research.google.com/github/maramgueye/portfolio_construction_theory/blob/main/portfolio_valuation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**REMINDER**: To run the code in a cell, you can make that cell active by placing the insertion point in it and then press Shift + Enter. When you do that, the next cell becomes active, so another Shift + Enter will execute the code in that new cell, and so on.

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

In [53]:
plt.rcParams.update({"axes.grid" : True})  # Make grid visible in plots

# Importing the Data (*)

**NOTE**: A star next to a section title like above means that the code in this section falls outside the scope of the chapter. You need to run the code in that section, for it creates objects (variables and functions) that we will use later, but you are not expected to read and understand it at this stage of the course. This code will not be commented on in class.

The stock data are stored in comma-separated value (csv) files, which are text files with fields (columns) delimited by a separator, here a comma. We use the function `read_csv` from Pandas to read every data file into a DataFrame, and we specify that the content of the column 'date should be used as the index of the DataFrame. We also tell Python to convert the strings from this column into Pandas dates. Python is usually able to infer the proper date format from the data, but it is safe to make it explicit that the dates are stored in the dd/mm/yyyy format in the file by specifying `dayfirst=True`. With `dayfirst=False`, the strings would be read as mm/dd/yyyy.

In [54]:
from google.colab import files
files.upload()
prc = pd.read_csv('prc.csv',
                  index_col='date', parse_dates=['date'], dayfirst=False)

Saving prc.csv to prc (1).csv

In [55]:
prc

,MICROSOFT CORP,GENERAL ELECTRIC CO,APPLE INC,JPMORGAN CHASE & CO,VISA INC
date,,,,,
2015-01-02,46.760,25.06,109.33,62.49,265.02
2015-01-05,46.325,24.60,106.25,60.55,259.17
2015-01-06,45.650,24.07,106.26,58.98,257.50
2015-01-07,46.230,24.08,107.75,59.07,260.95
2015-01-08,47.590,24.37,111.89,60.39,264.45
...,...,...,...,...,...
2025-12-24,488.020,316.75,273.81,329.17,355.14
2025-12-26,487.710,315.14,273.40,327.91,355.00
2025-12-29,487.100,311.58,273.76,323.75,354.61
2025-12-30,487.480,311.79,273.08,323.42,353.62
2025-12-31,483.620,308.03,271.86,322.22,350.71

We also read the dividend data, which we will occasionally use.

In [56]:
from google.colab import files
files.upload()
div = pd.read_csv('div_amt.csv',
                  index_col='date', parse_dates=['date'], dayfirst=False)

div

Saving div_amt.csv to div_amt (1).csv

,MICROSOFT CORP,GENERAL ELECTRIC CO,APPLE INC,JPMORGAN CHASE & CO,VISA INC
date,,,,,
2015-01-02,0.0,0.00,0.0,0.4,0.0
2015-01-05,0.0,0.00,0.0,0.0,0.0
2015-01-06,0.0,0.00,0.0,0.0,0.0
2015-01-07,0.0,0.00,0.0,0.0,0.0
2015-01-08,0.0,0.00,0.0,0.0,0.0
...,...,...,...,...,...
2025-12-24,0.0,0.00,0.0,0.0,0.0
2025-12-26,0.0,0.00,0.0,0.0,0.0
2025-12-29,0.0,0.36,0.0,0.0,0.0
2025-12-30,0.0,0.00,0.0,0.0,0.0
2025-12-31,0.0,0.00,0.0,0.0,0.0

Dividends are zero on most days, as companies typically pay dividends on a quarterly basis.

# A One-Period Example

In this section, we need the prices of the 5 stocks on two dates: January 2, 2015 and January 5, 2015. We store them in a Pandas DataFrame `prc_ex` with 2 rows (one for each date) and 5 columns. `loc` is the name of the accessor which allows us to access the rows and the columns of a DataFrame. We then use row-column indexation, with a comma (`,`) between the row and the column indices, and a colon (`:`) to refer to all columns.

In [59]:
prc_ex = prc.loc[['2015-01-02', '2015-01-05'], :]  # Create the array

prc_ex  # Display it for preview

,MICROSOFT CORP,GENERAL ELECTRIC CO,APPLE INC,JPMORGAN CHASE & CO,VISA INC
date,,,,,
2015-01-02,46.760,25.06,109.33,62.49,265.02
2015-01-05,46.325,24.60,106.25,60.55,259.17

For brevity, we refer to Jan. 2, 2015 as time 0, and to Jan. 15 as time 1.

The object `prc_ex` is a Pandas DataFrame, a data structure that is convenient to store time series data for multiple variables. It has two dimensions (rows and columns).

## Portfolio Value and Composition at Time 1

At time 0, we split \\$1,000 equally across the 5 stocks. The common dollar allocation is calculated as the initial portfolio value (\\$1,000) divided by the number of stocks. We collect the initial amount invested in each stock in a NumPy array `initial_amt`.

In [60]:
# TODO: Write your own calculation here.
N = 5
initial_amt= np.ones(N)*(1000/N)
initial_amt

array([200., 200., 200., 200., 200.])

Our code to create the NumPy array is correct but long to type and hard to read, because we repeat the variable name `initial_amt_per_stock` five times. This approach is inefficient, and would become infeasible if we had many stocks. To efficiently create an array of the initial dollar amounts, we can multiply the common dollar amount by an array of length $N$ whose elements are all equal to 1. The module NumPy provides us with a function `ones` that precisely does this. Do not forget to prefix the function name with the abbreviated module name, `np`.

In [61]:
# TODO: Write your own calculation here.

The initial percentage weights are

In [62]:
# TODO: Write your own calculation here.
initial_w= np.ones(N)* (1/N)
initial_w

array([0.2, 0.2, 0.2, 0.2, 0.2])

**Check:** Interpret your result and verify that it is consistent with the portfolio definitions.

Now, let us extract the initial prices, which are in the first row of the DataFrame `prc_ex`.

In [63]:
# TODO: Write your own calculation here.
#prc_ex.iloc[0,:]
initial_prices=prc_ex.iloc[0, :]
initial_prices

MICROSOFT CORP          46.76
GENERAL ELECTRIC CO     25.06
APPLE INC              109.33
JPMORGAN CHASE & CO     62.49
VISA INC               265.02
Name: 2015-01-02 00:00:00, dtype: float64

You may note that this object looks a little different from the DataFrame `prc_ex`. Indeed, it is a Pandas Series, rather than a DataFrame. A Series is a simpler structure than a DataFrame, as it has a single dimension, which is neither a row nor a column. Among other purposes, it is suited to store time series data for a single variable, or cross section data at a given date, as here. You can think of a Series as a NumPy array with named elements, and the names are useful to remember what every number represents.

We can then obtain the initial number of shares, by dividing the dollar amount in each stock by the share price.

In [64]:
# TODO: Write your own calculation here.
initial_number_of_shares= initial_amt/initial_prices
initial_number_of_shares

MICROSOFT CORP         4.277160
GENERAL ELECTRIC CO    7.980846
APPLE INC              1.829324
JPMORGAN CHASE & CO    3.200512
VISA INC               0.754660
Name: 2015-01-02 00:00:00, dtype: float64

Note that we can divide an array by another array of the same size. This is the *strongly* recommended method to divide every element of an array by the corresponding element of another, as this approach is much faster than to write a loop over the elements.

At the period end, the numbers of shares are identical, so the dollar amounts are

In [65]:
prc_ex

,MICROSOFT CORP,GENERAL ELECTRIC CO,APPLE INC,JPMORGAN CHASE & CO,VISA INC
date,,,,,
2015-01-02,46.760,25.06,109.33,62.49,265.02
2015-01-05,46.325,24.60,106.25,60.55,259.17

In [66]:
# TODO: Write your own calculation here.
end_prices=initial_number_of_shares*prc_ex.loc['2015-01-05']
end_prices

MICROSOFT CORP         198.139435
GENERAL ELECTRIC CO    196.328811
APPLE INC              194.365682
JPMORGAN CHASE & CO    193.791007
VISA INC               195.585239
dtype: float64

This object is again a Pandas Series from the module Pandas. Let us give it a name, `new_amt`, and calculate the portfolio value as the sum of the elements of the Series.

In [67]:
# TODO: Write your own calculation here.
new_amt=end_prices
new_amt

MICROSOFT CORP         198.139435
GENERAL ELECTRIC CO    196.328811
APPLE INC              194.365682
JPMORGAN CHASE & CO    193.791007
VISA INC               195.585239
dtype: float64

To calculate the sum of the new amounts, we use `sum`, which is a *method* of the Pandas Series class. To call a method on an object, we type the object name (`new_amt`), followed by a dot (`.`), the method name (`sum`) and a pair of round brackets (`()`). The bracket pair is left empty here, for the method does not expect other arguments than `new_amt`.

We can now calculate the portfolio weights at the period end:

In [68]:
# TODO: Write your own calculation here.
new_amt.sum()

np.float64(978.210173560328)

**Check:** Interpret your result and verify that it is consistent with the portfolio definitions.

We originally had an allocation of US1,000 but know it's US978.21 so we lost some money, individually each stock is lower than the US200 allocation we invested in it, so all stocks perform badly we some like JPMorgan performing worth than the other

In [69]:
# TODO: Write your own calculation here.

## Implementation Exercise: Reverting to an Equally Weighted Portfolio

our knew amount of money is ' new_amt.sum() '

In [ ]:
# Your code goes here
total= new_amt.sum()
new_alloc=np.ones(N)* (total/N)
new_alloc

array([195.64203471, 195.64203471, 195.64203471, 195.64203471,
       195.64203471])

In [ ]:
diff= new_alloc-new_amt
new_allocation_per_shares= new_amt+diff
new_allocation_per_shares

MICROSOFT CORP         195.642035
GENERAL ELECTRIC CO    195.642035
APPLE INC              195.642035
JPMORGAN CHASE & CO    195.642035
VISA INC               195.642035
dtype: float64

# Constituents' Returns and Portfolio Returns

## Calculating the Portfolio Return

To calculate the daily returns on the stocks, we can use the built-in DataFrame method `pct_change`. This function simply calculates the percent change in the values from a row to the next.

In [79]:
 prc_ex.pct_change()

,MICROSOFT CORP,GENERAL ELECTRIC CO,APPLE INC,JPMORGAN CHASE & CO,VISA INC
date,,,,,
2015-01-02,NaN,NaN,NaN,NaN,NaN
2015-01-05,-0.009303,-0.018356,-0.028172,-0.031045,-0.022074

The first row in the returned DataFrame is filled with NaN, which is the symbol for Not-a-Number. Indeed, there is no previous row for us to calculate a return from, so Python returns a missing value in this row. The second row, with the index 2015-01-05, contains the returns from Jan. 2, 2015 to Jan. 5, 2015.

In [78]:
# TODO: Write your own calculation here.
returns = prc_ex.pct_change().loc['2015-01-05']
returns

MICROSOFT CORP        -0.009303
GENERAL ELECTRIC CO   -0.018356
APPLE INC             -0.028172
JPMORGAN CHASE & CO   -0.031045
VISA INC              -0.022074
Name: 2015-01-05 00:00:00, dtype: float64

To calculate the portfolio return, we can apply the definition of the return:

In [83]:
# TODO: Write your own calculation here.
s1=prc_ex.loc['2015-01-05']
s0=prc_ex.loc['2015-01-02']
returns2= (s1-s0)/s0
returns2

MICROSOFT CORP        -0.009303
GENERAL ELECTRIC CO   -0.018356
APPLE INC             -0.028172
JPMORGAN CHASE & CO   -0.031045
VISA INC              -0.022074
dtype: float64

**Check:** Interpret your result and verify that it is consistent with the portfolio definitions.

#TODO
Nous avons bien les meme valeurs entre la formule et le pct_change

Now, let us recover the portfolio return by applying the dot product formula from the slides. The formula says that the portfolio return is the dot product of the initial weights and the vector of constituents' returns. Before we apply this formula, we must create a vector of constituents' returns over the investment period by extracting the second row of the above DataFrame. Recall that, according to Python's indexing convention, the second row has index 1, not 2.

In [85]:
# TODO: Write your own calculation here.
vector_of_constituents_returns=  prc_ex.pct_change().iloc[1,:]
vector_of_constituents_returns

MICROSOFT CORP        -0.009303
GENERAL ELECTRIC CO   -0.018356
APPLE INC             -0.028172
JPMORGAN CHASE & CO   -0.031045
VISA INC              -0.022074
Name: 2015-01-05 00:00:00, dtype: float64

The returned object is a Pandas Series indexed by the constituents' names. The dot product operator `@` will treat this Series as a 1-dimensional array, so we can take the dot product of the returns and the weights as follows:

In [86]:
initial_w

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [88]:
# TODO: Write your own calculation here.
portfolio_returns= initial_w @ vector_of_constituents_returns
portfolio_returns

np.float64(-0.02178982643967189)

**Check:** Interpret your result and verify that it is consistent with the portfolio definitions.

## Implementation Exercise: Checking the Update Formula

In [ ]:
# Your code goes here

# Stock Portfolio Valuation With Corporate Actions

We now want to calculate the daily values of the portfolio over the entire sample, from Jan. 2, 2015 through the sample end (Dec. 31, 2025). The key assumption is that the portfolio is buy-and-hold and self-financing over the investment period.

## Adjusting Stock Returns for Splits

To illustrate how stock returns are adjusted for corporate actions, let us consider the Apple stock. On August 31, 2020, this stock underwent a 4:1 split, meaning that every share became a bundle of 4 shares. Consequently, the price was divided by a factor of 4 on that day.

In [ ]:
prc['APPLE INC']  # Apple stock prices only

In [ ]:
prc_apple_split = prc['APPLE INC']['2020-08-28' : '2020-08-31']  # Apple stock prices on Aug. 28 and 31, 2020

prc_apple_split

Calculating the return without accounting for the split leads to a misleading large negative value:

In [ ]:
# TODO: Write your own calculation here.

To properly calculate the return, we must multiply the final price by 4, as every share became 4 shares:

In [ ]:
# TODO: Write your own calculation here.

## Adjusting Stock Returns for Splits

We now want to calculate the returns on the Apple stock from Nov. 7 to Nov. 10, 2025, both without and with an adjustment for the dividend.

In [ ]:
prc_apple_div = prc['APPLE INC']['2025-11-07' : '2025-11-10']

prc_apple_div

In [ ]:
div_apple = div['APPLE INC']['2025-11-10']

div_apple

The **price return** from Nov. 7 to Nov. 10 is obtained by applying the regular return formula:

In [ ]:
# TODO: Write your own calculation here.

To get the **total return**, we add the dividend to the final share price in the numerator:

In [ ]:
# TODO: Write your own calculation here.

Neither of these formulas is "right" or "wrong"; they measure two different returns, and both notions of returns can be used for portfolio valuation purposes, depending on what the portfolio manager does with the dividends (distribute them or reinvest them).

## Importing Data for the Exercise (*)

In [ ]:
adj_prc_splits = pd.read_csv('adj_prc_splits.csv',
                             index_col='date', parse_dates=['date'], dayfirst=False)

adj_prc_splits  # Only splits

In [ ]:
adj_prc_splits_div = pd.read_csv('adj_prc_splits_div.csv',
                                 index_col='date', parse_dates=['date'], dayfirst=False)

adj_prc_splits_div  # Splits and dividends

In [ ]:
div = pd.read_csv('div_amt.csv',
                  index_col='date', parse_dates=['date'], dayfirst=False)

div

## Buy-and-Hold Portfolio with Reinvested Dividends

In [ ]:
# Your code goes here

## Buy-and-Hold Portfolio with Distributed Dividends

In [ ]:
# Your code goes here

## Calculating the Distributed Dividends (*)

In [ ]:
# Your code goes here

# Weight Calculation Exercise

In [ ]:
# Your code goes here

# Fixed-Mix Portfolio Valuation Exercise

In [ ]:
# Your code goes here